version: '3.8'
services:
    messenger-ui:
        build: .
        ports: -'3000:3000'
        # environment:
        #     - VITE_API_URL=http://localhost:8080/api/v1
        #     - VITE_SOCKET_URL=http://localhost:8080/
        env_file:
            - ./.env
        volumes:
            - ./src:/app/src
