const SOCKET_EVENT = {
    RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
    NEW_USER: 'NEW_USER',

    SEND_VIDEO_CALL_RECEIVER_ID: 'SEND_VIDEO_CALL_RECEIVER_ID',
    RECEIVE_VIDEO_CALL_RECEIVER_ID: 'RECEIVE_VIDEO_CALL_RECEIVER_ID',
    ANSWER_CALL: 'ANSWER_CALL',
};

export default SOCKET_EVENT;
