import { IAuth } from './modules/auth/models/auth';
import { IFriend } from './modules/friends/models/friend';
import { IMessage } from './modules/messages/models/message';

export const user: IAuth = {
    id: 4,
    avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
    firstName: 'Shogun',
    lastName: 'Raiden',
    tick: true,
    username: 'raiden.shogun',
    userRoleId: 2,
    email: 'email',
    accessToken: 'email',
};

export const messages: IMessage[] = [
    {
        id: 1,
        content: 'Raiden Shogun',
        createdDate: null as any,
        senderDetail: {
            id: 1,
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        },
        receiverDetail: {
            id: 2,
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1693641489/Screenshot_2023-09-02_145746_c05rtd.png',
        },
    },
    {
        id: 2,
        content: 'Kafka',
        createdDate: null as any,
        senderDetail: {
            id: 2,
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1693641489/Screenshot_2023-09-02_145746_c05rtd.png',
        },
        receiverDetail: {
            id: 1,
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        },
    },
    {
        id: 3,
        content: 'Raiden Shogun',
        createdDate: null as any,
        senderDetail: {
            id: 1,
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        },
        receiverDetail: {
            id: 2,
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1693641489/Screenshot_2023-09-02_145746_c05rtd.png',
        },
    },
    {
        id: 4,
        content: 'Raiden Shogun',
        createdDate: null as any,
        senderDetail: {
            id: 2,
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1693641489/Screenshot_2023-09-02_145746_c05rtd.png',
        },
        receiverDetail: {
            id: 1,
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        },
    },
    {
        id: 5,
        content: 'Raiden Shogun',
        createdDate: null as any,
        senderDetail: {
            id: 1,
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        },
        receiverDetail: {
            id: 2,
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1693641489/Screenshot_2023-09-02_145746_c05rtd.png',
        },
    },
    {
        id: 6,
        content:
            'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        createdDate: null as any,
        receiverDetail: {
            id: 2,
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1693641489/Screenshot_2023-09-02_145746_c05rtd.png',
        },
        senderDetail: {
            id: 1,
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        },
    },
    {
        id: 7,
        content:
            'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        createdDate: null as any,
        receiverDetail: {
            id: 1,
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        },
        senderDetail: {
            id: 2,
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1693641489/Screenshot_2023-09-02_145746_c05rtd.png',
        },
    },
];

export const receiver = {
    id: 4,
    avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
    firstName: 'Shogun',
    lastName: 'Raiden',
    tick: true,
    username: 'raiden.shogun',
    lastestMessage: 'Testing',
};

export const friendList: IFriend[] = [
    {
        id: 1,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 2,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 3,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
    {
        id: 4,
        avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1653748550/raiden-crying_lr8dfp.jpg',
        firstName: 'Shogun',
        lastName: 'Raiden',
        tick: true,
        username: 'raiden.shogun',
        lastestMessage: 'Testing',
    },
];
